### ISSUE TITLE
`_print_elapsed_time` has been moved to into a submodule since sklearn v1.5

### ISSUE THREAD

**Issue by mchikyt3** [scikit-learn-contrib/skdag#33]
Since sklearn v1.5, the `_print_elapsed_time` function has been moved to into `utils._user_interface`. Therefore, it is needed to check the version of sklearn in order to import `_print_elapsed_time` from the correct module. [#28662](https://github.com/scikit-learn/scikit-learn/pull/28662)

**Comment by big-o** [comment]
Thanks for the contribution! I've released v0.0.7 which includes your fix. Closing.
